# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stedman Halliday â€¢ Multimedia Design
author: Stedman Halliday
email: stedman.rh@gmail.com
description: Portfolio and contact information for Southern California based graphic and multimedia designer Stedman Halliday
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stedmanhalliday.com" # the base hostname & protocol for your site
twitter_username:
github_username:  stedmanrh

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      #type optional
    values:
      icon-link: /bootstrap/img/link.png
      icon-phone: /bootstrap/img/phone.png
